services:
  admin_panel:
    build:
      context: ./admin_panel
      dockerfile: Dockerfile
    container_name: admin_panel
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./admin_panel/.env.production
    volumes:
      - ./admin_panel/uploads:/app/public/uploads

  public_portal:
    build:
      context: ./public_portal
      dockerfile: Dockerfile
    container_name: public_portal
    restart: unless-stopped
    depends_on:
      - admin_panel
    ports:
      - "3001:3001"
    env_file:
      - ./public_portal/.env.production
